### ISSUE TITLE
Cannot import ramda in the browser with native modules

### ISSUE THREAD

**Issue by Tim1023** [ramda/ramda#2680]
_index.html_
`<script src="index.js" type="module"></script>
`
_index.js_
`import R from './node_modules/ramda/es/index.js';
`
_console_
`GET http://ramda-playground.test/node_modules/ramda/es/F net::ERR_ABORTED 404 (Not Found)...`

I installed ramda with npm. The problem may caused by all the js files imported not ended with `.js` in `node_modules/ramda/es/`

**Comment by CrossEye** [comment]
Thank you for the report.  We'll look into it.

I haven't yet tried modules in the browser.  Is there a reason that you would want to include the entire library this way?  I would assume that the usual process would be to import those functions you want.  That doesn't mean that I don't think we should fix this if we can, but is what you're doing considered usual?

**Comment by Tim1023** [comment]
@CrossEye Also have tried import functions dynamically, like `import {replace, __} from './node_modules/ramda/es/index.js';` but still showing the same error.

 I think modules in the browser getting more and more popular these days since all the modern browser has supported native modules, and I also have tried same thing in loadsh which is running well.
`<script type="module">
  import cloneDeep from 'https://unpkg.com/lodash-es/cloneDeep'
</script>`
