### ISSUE TITLE
Ramda named imports not working as expected on Node project with ES Modules enabled

### ISSUE THREAD

**Issue by manuscriptmastr** [ramda/ramda#3019]
Hi friends! I have been publishing some vanilla Node packages with Ramda as a dependency. I'm really excited about ES Modules and have set the `"type": "module"` flag for these projects (Node 13.2+), but using libraries like ESM and Pika to make them backwards-compatible. I keep getting stumped by an error when I import named Ramda functions without fancy bundling (Webpack). [Full repo here](https://github.com/manuscriptmastr/min-retry), but TL;DR:
```js
// index.js
import {
  anyPass,
  both,
  complement,
  compose,
  constructN,
  curry,
  is,
  ifElse,
  invoker,
  map,
  propEq,
  when,
  type
} from 'ramda';

// Console
node . // 13.2 and 14 give the same error
file:///{path to project}/src/index.js:9
  is,
  ^^
SyntaxError: The requested module 'ramda' does not provide an export named 'is'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

Ironically, when I tweak the statement to `import R from 'ramda'; const { ... } = R;`, I have no problems running it locally. (It seems weird that this even works in `"type": "module"` mode given there is no default export from `node_modules/ramda/es/index.js` that I can see in the source code.)

However, when I publish the package and use it in a Webpack-configured project (my NPM package has the `"module"` flag set to the ES Module file), I am given the error `Attempted import error: 'ramda' does not contain a default export (imported as 'R')`.

I would think that `import { func1, func2, func3 } from 'ramda'` is the correct way to import in both scenarios, but it doesn't seem to be the case. Any thoughts why this is happening?

**Comment by CrossEye** [comment]
I always ping @Andarist when these things come up, because he knows much more than I do about the bundling.  

@Andarist, do  you have thoughts on this and/or time to investigate?

**Comment by Andarist** [comment]
I think this has been fixed by https://github.com/ramda/ramda/pull/2999 , but it has not yet been published.

**Comment by manuscriptmastr** [comment]
Oh nice! Looks _very_ familiar 😆 the `export` and `module` sections looked correct FWIW!

**Comment by mikestopcontinues** [comment]
Any ETA on the release? My fix for this problem is causing issues with another library. 😢

**Comment by CrossEye** [comment]
Not yet.  But I'll see if we can publish something soon.

**Comment by mikestopcontinues** [comment]
#2999 had fixed the original issue in my case with v.0.27.1, but it seems the problem really isn't resolved under the hood. I've got a version of the issue now where my app requires a package that depends on ramda. My app bundles with webpack/babel, and requests the 'module' version of my package. 

Since I rely on `babel-plugin-ramda`, I just `import R from 'ramda'`. In my package, this causes the error `Attempted import error: 'ramda' does not contain a default export (imported as 'R')`, even though the very same line doesn't cause an issue in my app (since #2999).

Here's what my package.json looks like in the package. I don't know which field webpack looks at, but it's one of the `index.module.js` ones...

```json
{
  "main": "./dist/index.js",
  "jsnext:main": "./dist/index.modern.js",
  "module": "./dist/index.module.js",
  "syntax": {
    "esmodules": "./dist/index.modern.js"
  },
  "exports": {
    ".": {
      "browser": "./dist/index.module.js",
      "import": "./dist/index.module.js",
      "require": "./dist/index.js"
    }
  },
}
```

I hope this adds a bit of context to the issue...

**Comment by Andarist** [comment]
> import R from 'ramda'

I believe this has been deprecated a quite long time ago already. `ramda` has no default export fo the error you are seeing is perfectly valid. Please check with `import * as R from 'ramda'`

**Comment by mikestopcontinues** [comment]
Thanks. That works. Now that you mention it, I suspect `* as R` replaces the need for the babel plugin with a bundler's normal tree shaking.

**Comment by Andarist** [comment]
Yes - when using treeshakers there shouldnt a need for this Babel plugin with the newest version of Ramda. When I've converted the codebase to ES modules I've validated this against both webpack and Rollup and they did a great job at tree-shaking Ramda out of the box back then.
